# clang-tidy configuration file
# Based on Google C++ Style Guide

Checks: >
  google-*,
  modernize-*,
  readability-*,
  performance-*,
  bugprone-*,
  -modernize-use-trailing-return-type,
  -readability-braces-around-statements,
  -readability-magic-numbers,
  -google-readability-braces-around-statements,
  -google-readability-todo

CheckOptions:
  - key: readability-identifier-naming.ClassCase
    value: CamelCase
  - key: readability-identifier-naming.ClassPrefix
    value: ''
  - key: readability-identifier-naming.ClassSuffix
    value: ''
  - key: readability-identifier-naming.FunctionCase
    value: CamelCase
  - key: readability-identifier-naming.MemberCase
    value: lower_case
  - key: readability-identifier-naming.MemberSuffix
    value: '_'
  - key: readability-identifier-naming.ParameterCase
    value: lower_case
  - key: readability-identifier-naming.VariableCase
    value: lower_case
  - key: readability-identifier-naming.ConstantCase
    value: UPPER_CASE
  - key: readability-identifier-naming.EnumConstantCase
    value: UPPER_CASE
  - key: readability-identifier-naming.MacroDefinitionCase
    value: UPPER_CASE
  - key: google-readability-function-size.StatementThreshold
    value: 800
  - key: google-readability-function-size.BranchThreshold
    value: 100

HeaderFilterRegex: '.*'
AnalyzeTemporaryDtors: false
FormatStyle: google